version: '3.1'
services:
  postgree-db:
    image: 'postgres:13.1'
    container_name: sentry-db
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_sentry